### ISSUE TITLE
error，请教您一下这个问题

### ISSUE THREAD

**Issue by yudadabing** [Ash-Zheng/License-Plate-Detection-and-Recognition#2]
4285
1072
Traceback (most recent call last):
  File "Train_number.py", line 36, in <module>
    images, labels = dataiter.next()
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\yudadabing\Desktop\License-Plate-Detection-and-Recognition-master\License-Plate-Detection-and-Recognition-master\dataload.py", line 78, in __getitem__
    label = int(path_list[-2])
ValueError: invalid literal for int() with base 10: 'num_letter'

**Comment by yudadabing** [comment]
ValueError: invalid literal for int() with base 10: 'data/train_images/training-set/num_letter/12'

**Comment by yudadabing** [comment]
4285
1072
tensor([24, 10, 20, 31])
Traceback (most recent call last):
  File "Train_number.py", line 54, in <module>
    for i, data in enumerate(trainloader, 0):
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\yudadabing\Desktop\陈晨师兄车牌识别\License-Plate-Detection-and-Recognition-master\License-Plate-Detection-and-Recognition-master\dataload.py", line 71, in __getitem__
    if img[i, j] < 0:
TypeError: 'NoneType' object is not subscriptable
